export const sensitiveWords = [
  'violence',
  'kill',
  'hurt',
  'harm',
  'assault',
  'weapon',
  'gunshot',
  'murder',
  'porn',
  'sex',
  'erotic',
  'nudity',
  'adult',
  'explicit',
  'fetish',
  'racist slurs',
  'derogatory terms',
  'offensive language',
  'racial epithets',
  'homophobic slurs',
  'sexist language',
  'derogatory terms for disabilities',
  'terrorism',
  'terrorist',
  'hate speech',
  'radicalization',
  'extremist',
  'propaganda',
  'blasphemy',
  'sacrilege',
  'personal information',
  'identity theft',
  'hacking',
  'phishing',
  'scam',
  'fraud',
  'illegal activities',
  'criminal activity',
  'drugs',
  'alcohol',
  'tobacco',
  'gambling',
  'violence',
  'pornographic content',
  'explicit language',
  'mature themes',
  'child',
  'pedophile',
  'pedophilia',
  'child molester',
  'child abuse',
  'child exploitation',
  'child pornography',
  'underage sex',
  'minor exploitation',
  'jailbait',
  'teen model',
  'kid por',
  'kiddie porn',
  'cchildren',
  'topless',
  'undress',
  'naked',
  'nude',
  'penis',
  'vagina',
  'kids porn',
  'childrenporn',
  'bdsm',
  'without clothes',
  'no dress',
  'deep nude',
  'tit',
  'tits',
  'breasts',
  'ass',
  'pussy',
  'cock',
  'dick',
  'dicks',
  'cocks',
  'nipple',
  'nipples',
  'butt',
  'butts',
  'no clothes',
  'no pants',
  'no underwear',
  'slutty',
  'slut',
];
