export const HENTAI_GALLARY = [];

export const HENTAI_MODELS = [
  { key: 'female:basic', label: 'Female: Anime Basic' },
  { key: 'female:realistic', label: 'Female: Anime Realistic' },
  { key: 'female:detail', label: 'Female: Anime Detailed' },
  { key: 'female:hd', label: 'Female: Anime HD' },
  { key: 'male:basic', label: 'Male:Anime Basic' },
  { key: 'male:realistic', label: 'Male:Anime Realistic' },
  { key: 'male:detail', label: 'Male:Anime Detailed' },
  { key: 'male:hd', label: 'Male: Anime HD' },
];

export const HENTAI_TAGS: Record<
  string,
  {
    label: string;
    values: string[];
    type?: 'radio' | 'checkbox';
  }
> = {
  anime_base: {
    label: 'Character',
    values: [
      'Elf',
      'Furry',
      'Knight',
      'Man',
      'Mature',
      'Mermaid',
      'Ninja',
      'Random',
      'Vampire',
      'Woman',
    ],
    type: 'radio',
  },
  anime_action: {
    label: 'Posture',
    values: [
      'Arched Back',
      'Arm Raised',
      'Cat Paw Pose',
      'Crouch',
      'Head Tilt',
      'Hugging Pillow',
      'Hugging-legs',
      'Indian Style',
      'Kneeling',
      'On Back',
      'Side-sitting',
      'Sitting',
      'Stretching',
    ],
    type: 'radio',
  },
  anime_tags: {
    label: 'Features',
    values: [
      'Antler',
      'Cat Ears',
      'Dog Ears',
      'Furry',
      'Glasses',
      'Hair Band',
      'Hair Pin',
    ],
    type: 'radio',
  },
  body: {
    label: 'Body',
    values: [
      'Abs',
      'BBW',
      'Chubby',
      'Dark Skin',
      'Doll Joints',
      'Fairy Wings',
      'Long Legs',
      'Mechanical Wings',
      'Muscular',
      'Perfect Body',
      'Pregnant',
      'Short',
      'Skinny',
      'Sunburnt',
      'Tall',
      'Tattoos',
      'Wide Hips',
    ],
    type: 'checkbox',
  },
  skin_color: {
    label: 'Skin Color',
    values: [
      'Dark Skin',
      'Porcelain',
      'Shiny Skin',
      'Tan',
      'Tanlines',
      'Tattoo',
    ],
  },
  hair_color: {
    label: 'Hair Color',
    values: [
      'Aqua Hair',
      'Black Hair',
      'Blonde',
      'Blue Hair',
      'Brunette',
      'Ginger Hair',
      'Green Hair',
      'Pink Hair',
      'Purple Hair',
      'Red Hair',
      'Sliver Hair',
      'White Hair',
    ],
    type: 'radio',
  },
  hair_style: {
    label: 'Hair Style',
    values: [
      'Asymmetrical Bangs',
      'Asymmetrical Hair',
      'Bangs',
      'Blunt Bangs',
      'Bobcut',
      'Braided',
      'Curly Hair',
      'Flipped Hair',
      'Hair Bun',
      'Long Hair',
      'Medium Hair',
      'Messy Hair',
      'Ponytail',
      'Ringlets',
      'Short Hair',
      'Slicked',
      'Straight Hair',
      'Swept Bangs',
      'Twintails',
      'Wavy Hair',
    ],
    type: 'radio',
  },
  Facial_Expr: {
    label: 'Facial Expression',
    values: [
      'Angry',
      'Blush',
      'Crying',
      'Disdain',
      'Embarrassed',
      'Evil Smile',
      'Light Smile',
      'Mouth Open',
      'Sad',
      'Scared Expression',
      'Seductive Smile',
      'Smile',
      'Smirk',
      'Tongue Out',
    ],
    type: 'radio',
  },
  view: {
    label: 'View',
    values: ['Front View', 'Side View', 'Back View', 'Close-Up View'],
    type: 'radio',
  },
  setting: {
    label: 'Setting',
    values: [
      'Backyard',
      'Balcony',
      'Bar',
      'Bathroom',
      'Beach',
      'Bedroom',
      'Bus',
      'Cafe',
      'Car',
      'Casino',
      'Cave',
      'Changing Room',
      'Church',
      'Classroom',
      'Club',
      'Couch',
      'Desert',
      'Forest',
      'Grocery',
      'Gym',
      'Hospital',
      'Hot Tub',
      'Jungle',
      'Kitchen',
      'Lack',
      'Library',
      'Livingroom',
      'Locker Room',
      'Mall',
      'Meadow',
      'Moon',
      'Mountain',
      'Oasis',
      'Office',
      'Onsen',
      'Party',
      'Pool',
      'Prison',
      'Restaurant',
      'Sauna',
      'Shower',
      'Snow',
      'Stage',
      'Street',
      'Tent',
      'Train',
      'Underwater',
      'Wedding',
      'Yacht',
    ],
    type: 'radio',
  },
  clothing: {
    label: 'Clothing',
    values: [
      'Angel',
      'Apron',
      'Bar',
      'Basketball',
      'Bathrobe',
      'Beach Volleyball',
      'Bikini',
      'Blouse',
      'Bodypaint',
      'Bomber',
      'Boots',
      'Bow Tie',
      'Casual',
      'Cheerleader',
      'Chemise',
      'Clown',
      'Corset',
      'Cosplay',
      'Devil',
      'Doctor',
      'Dress',
      'Face Mask',
      'Fantasy Armor',
      'Firefighter',
      'Fishnet',
      'Flamenco Dancerpolo',
      'Flight Attendant',
      'Fur',
      'Gloves',
      'Golf',
      'Goth',
      'Halloween',
      'Harem Pants',
      'Harlequin',
      'Hat',
      'High Heels',
      'Hight Socks',
      'Hip Hop',
      'Idol Stage Custom',
      'JK',
      'Jacket',
      'Jeans',
      'Jumpsuit',
      'Kilt',
      'Kimono',
      'Lab Coat',
      'Latex',
      'Leather',
      'Lingerie',
      'Lolita',
      'Long Skirt',
      'Lumberjack',
      'Maid',
      'Martial Arts',
      'Mech Suit',
      'Medieval',
      'Mesh',
      'Micro Skirt',
      'Microkini',
      'Miko Attire',
      'Military',
      'Mini Skirt',
      'Nightgown',
      'Ninja',
      'Niqab',
      'Nun',
      'Nurse',
      'One Piece Swimsuit',
      'Onesie',
      'Pajamas',
      'Panties',
      'Pantyhose',
      'Parka',
      'Pilot',
      'Pirate',
      'Police',
      'Polo',
      'Professor',
      'Push-Up Bra',
      'Race Driver',
      'Rama',
      'Rococo Dress',
      'Sailor',
      'Santa',
      'Sari',
      'Satin',
      'Scarf',
      'Sci-Fi Armor',
      'Secretary',
      'Shirt',
      'Short Shorts',
      'Soccer',
      'Space Suit',
      'Sports Bra',
      'Sports',
      'Steampunk',
      'Stockings',
      'Stylish',
      'Suit',
      'Sundress',
      'Superhero',
      'Suspender Belt',
      'Sweater',
      'Tailcoat',
      'Tank Top',
      'Teacher',
      'Tennis',
      'Thigh Socks',
      'Tie',
      'Traditional',
      'Trench Coat',
      'Tribal',
      'Tunic',
      'Underwear',
      'Vampire',
      'Viking',
      'Waitress',
      'Wedding',
      'Western',
      'Witch',
      'Yoga Pants',
    ],
    type: 'checkbox',
  },
  advanced: {
    label: 'Advanced Style',
    values: ['Alternative', 'Detailed', 'Simple'],
    type: 'radio',
  },
};
